# ?? ?? ??
server:
  port: 8111
  servlet:
    encoding:
      charset: UTF-8

# mysql, jpa ??
spring:
  application:
    name: team
  config:
    import: optional:file:.env[.properties]
  datasource:
    #    url: jdbc:mysql://mysql-service.default.svc.cluster.local:3306/goruna
    url: jdbc:log4jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: ${DRIVER_CLASS_NAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#cloud:
#  aws:
#    s3:
#      bucket: goruna
#    stack:
#      auto: false
#    region:
#      static: us-west-1
#    credentials:
#      access-key: ${AWS_ACCESS_KEY}
#      secret-key: ${AWS_SECRET_KEY}

# logging ?? (?? ???)
logging:
  file:
    path: /var/logs/team
  level:
    root: info
    org.springframework.web: info
    com.zaxxer.hikari: info
    log4jdbc.log4j2: error
    jdbc.sqlonly: info
    jdbc.resultsettable: info
    jdbc.connection: info

springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none